NIFTY = "NIFTY"
BANKNIFTY = "BANKNIFTY"
MIDNIFTY = "MIDCPNIFTY"
SEND_TELEGRAM_MESSAGE = True
TELEGRAM_TOKEN = "7045906590:AAGK5-gfPyqXXFx1cZJgfl9xUXcXcTBiUsI"
TELEGRAM_CHATID = "1000631227"

SYMBOL_SETTINGS = {
    "NIFTY": {
        "TRADE_TF": 10,
        "POSITION_TYPE": None,
        "CURR_SECURITYID" : None,
        "OPEN_POSITION": False,
        "ENTRY_PRICE": None 
    },
    "BANKNIFTY": {
        "TRADE_TF": 15,
        "POSITION_TYPE": None,
        "CURR_SECURITYID" : None,
        "OPEN_POSITION": False,
        "ENTRY_PRICE": None 
    }
}